const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const LOGIN_ERROR = 'LOGIN_ERROR';

const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
const REGISTER_ERROR = 'REGISTER_ERROR';

const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
const LOGOUT_ERROR = 'LOGOUT_ERROR';

export default {
	LOGIN_SUCCESS,
	LOGIN_ERROR,
	REGISTER_SUCCESS,
	REGISTER_ERROR,
	LOGOUT_SUCCESS,
	LOGOUT_ERROR,
} as const;
